import { queryPerplexity } from "./client";
import type { Incident, IncidentEvent, RootCauseAnalysis, Remediation } from "@/types";

/**
 * Generates a complete, blameless post-mortem document following the
 * Google SRE template. Returns Markdown.
 */
export async function generatePostMortem(
  incident: Incident,
  events: IncidentEvent[],
  rootCause: RootCauseAnalysis,
  remediations: Remediation[]
): Promise<string> {
  const appliedRemediations = remediations.filter((r) => r.status === "applied");
  const skippedRemediations = remediations.filter((r) => r.status === "skipped");
  const suggestedRemediations = remediations.filter((r) => r.status === "suggested");

  const { content } = await queryPerplexity({
    model: "sonar-pro", // Pro is sufficient for writing; save reasoning credits
    messages: [
      {
        role: "system",
        content: `You are a Staff SRE writing a blameless post-mortem for a production incident.

Follow the Google SRE post-mortem template exactly:

# Post-Mortem: [Incident Title]
**Date:** [date]  
**Duration:** [duration]  
**Severity:** [sev level]  
**Author:** Cloudscape AI (auto-generated, requires human review)

## Summary
2-3 sentence executive summary.

## Impact
- What users/services were affected
- Duration of impact
- Quantified impact (error rates, latency, etc.)

## Root Cause
Clear, technical explanation. No blame.

## Trigger
What specific event set the failure in motion.

## Detection
How the incident was detected (alarm, user report, etc.) and how long it took.

## Timeline
Chronological list of events from trigger to resolution.

## Resolution
What was done to restore service.

## Action Items
| Action | Type | Owner | Due Date |
|--------|------|-------|----------|
| ... | prevent/detect/mitigate | TBD | TBD |

## Lessons Learned
### What went well
### What went wrong
### Where we got lucky

---
*This post-mortem was auto-generated by Cloudscape. Review and assign action item owners before publishing.*

Write in clear, professional prose. Be specific with technical details. Never assign blame to individuals.`,
      },
      {
        role: "user",
        content: `INCIDENT: ${incident.title}
SEVERITY: ${incident.severity}
STARTED: ${incident.started_at}
RESOLVED: ${incident.resolved_at ?? "ongoing"}
SYMPTOM: ${incident.symptom}

ROOT CAUSE:
${rootCause.root_cause}
Category: ${rootCause.category}
Contributing factors: ${rootCause.contributing_factors.join(", ")}
AWS outage involved: ${rootCause.is_aws_outage}

TIMELINE:
${events.map((e) => `${e.timestamp} [${e.source}] ${e.content}`).join("\n")}

REMEDIATIONS APPLIED:
${appliedRemediations.map((r) => `- ${r.title}: ${r.description}`).join("\n") || "None yet"}

REMEDIATIONS SUGGESTED (NOT YET APPLIED):
${suggestedRemediations.map((r) => `- ${r.title}: ${r.description}`).join("\n") || "None"}

REMEDIATIONS SKIPPED:
${skippedRemediations.map((r) => `- ${r.title}: ${r.description}`).join("\n") || "None"}

Generate the full post-mortem document in Markdown.`,
      },
    ],
    searchContextSize: "low", // Post-mortem doesn't need heavy web search
    temperature: 0.3,
    maxTokens: 4096,
  });

  return content;
}
